using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.Json;

namespace BokWorks.AppConfigGenerator;

[Generator]
public class AppSettingsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var isRelease = context.AnalyzerConfigOptionsProvider.Select((opts, _) =>
        {
            opts.GlobalOptions.TryGetValue("build_property.Configuration", out var config);
            return string.Equals(config, "Release", StringComparison.OrdinalIgnoreCase);
        });

        // Assembly name is already in the compilation — no CompilerVisibleProperty needed
        var assemblyName = context.CompilationProvider
            .Select((c, _) => c.AssemblyName ?? "App");

        var settingsFiles = context.AdditionalTextsProvider
            .Where(f =>
            {
                var name = Path.GetFileName(f.Path);
                return name.Equals("appsettings.json", StringComparison.OrdinalIgnoreCase)
                    || name.Equals("appsettings.Loc.json", StringComparison.OrdinalIgnoreCase);
            });

        var combined = settingsFiles.Collect()
            .Combine(isRelease)
            .Combine(assemblyName);

        context.RegisterSourceOutput(combined, (ctx, data) =>
        {
            var ((files, release), asmName) = data;

            AdditionalText? baseFile = null, locFile = null;
            foreach (var f in files)
            {
                var name = Path.GetFileName(f.Path);
                if (name.Equals("appsettings.json", StringComparison.OrdinalIgnoreCase)) baseFile = f;
                if (name.Equals("appsettings.Loc.json", StringComparison.OrdinalIgnoreCase)) locFile = f;
            }

            if (baseFile == null) return;

            var baseJson = baseFile.GetText()?.ToString() ?? "{}";

            // In Release, Loc is ignored entirely — even if somehow present
            var locJson = (!release && locFile != null)
                ? locFile.GetText()?.ToString() ?? "{}"
                : "{}";

            var merged = Merge(locJson, baseJson);   // base wins on conflict
            var source = GenerateClass(merged, asmName);

            ctx.AddSource("AppConfig.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// Loc supplies fallback values; base overwrites on any key collision (deep).
    private static Dictionary<string, object?> Merge(string fallbackJson, string dominantJson)
    {
        var fallback = ParseObject(JsonDocument.Parse(fallbackJson).RootElement);
        var dominant = ParseObject(JsonDocument.Parse(dominantJson).RootElement);
        return DeepMerge(fallback, dominant);   // dominant wins
    }

    private static Dictionary<string, object?> DeepMerge(
        Dictionary<string, object?> fallback,
        Dictionary<string, object?> dominant)
    {
        // Start from fallback, then let dominant overwrite
        var result = new Dictionary<string, object?>(fallback);
        foreach (var kvp in dominant)
        {
            var key = kvp.Key;
            var dominantValue = kvp.Value;

            if (dominantValue is Dictionary<string, object?> dominantNested
             && result.TryGetValue(key, out var existing)
             && existing is Dictionary<string, object?> fallbackNested)
            {
                // Both sides have an object at this key — recurse
                result[key] = DeepMerge(fallbackNested, dominantNested);
            }
            else
            {
                // Dominant wins outright
                result[key] = dominantValue;
            }
        }
        return result;
    }

    private static Dictionary<string, object?> ParseObject(JsonElement el)
    {
        var dict = new Dictionary<string, object?>();
        if (el.ValueKind != JsonValueKind.Object) return dict;
        foreach (var prop in el.EnumerateObject())
            dict[prop.Name] = ParseValue(prop.Value);
        return dict;
    }

    private static object? ParseValue(JsonElement el) => el.ValueKind switch
    {
        JsonValueKind.Object => ParseObject(el),
        JsonValueKind.String => el.GetString(),
        JsonValueKind.True => true,
        JsonValueKind.False => false,
        JsonValueKind.Number when el.TryGetInt64(out var i) => i,
        JsonValueKind.Number => el.GetDouble(),
        _ => null
    };

    private static string GenerateClass(Dictionary<string, object?> values, string assemblyName)
    {
        // Derive a safe root namespace from the assembly name
        var ns = assemblyName.Replace('-', '_');

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Source: appsettings.json (assembly: {assemblyName})");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}.Config");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class AppConfig");
        sb.AppendLine("    {");
        WriteMembers(sb, values, indent: 2);
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void WriteMembers(StringBuilder sb, Dictionary<string, object?> dict, int indent)
    {
        var pad = new string(' ', indent * 4);
        foreach (var kvp in dict)
        {
            var key = kvp.Key;
            var value = kvp.Value;

            var name = ToPascalCase(key);
            switch (value)
            {
                case Dictionary<string, object?> nested:
                    sb.AppendLine($"{pad}public static class {name}");
                    sb.AppendLine($"{pad}{{");
                    WriteMembers(sb, nested, indent + 1);
                    sb.AppendLine($"{pad}}}");
                    break;
                case string s:
                    sb.AppendLine($"{pad}public const string {name} = \"{Escape(s)}\";");
                    break;
                case bool b:
                    sb.AppendLine($"{pad}public const bool {name} = {(b ? "true" : "false")};");
                    break;
                case long i:
                    sb.AppendLine($"{pad}public const long {name} = {i}L;");
                    break;
                case double d:
                    sb.AppendLine($"{pad}public const double {name} = {d};");
                    break;
            }
        }
    }

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");

    private static string ToPascalCase(string s) =>
        string.IsNullOrEmpty(s) ? s : char.ToUpper(s[0]) + s.Substring(1);
}