name: CI
run-name: '${{ github.event.head_commit.message }} (CI Run #${{ github.run_number }})'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            10.0.x
      - name: Restore
        run: dotnet restore Src/BokWorks.AppConfigGenerator.slnx
      - name: Build
        run: dotnet build Src/BokWorks.AppConfigGenerator.slnx -v minimal
      - name: Test
        run: dotnet test Src/BokWorks.AppConfigGenerator.slnx -v minimal